[package]
name = "migux_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
migux_config = { path = "../migux_config" }
migux_http = { path = "../migux_http" }

anyhow = { workspace = true }
dashmap = { workspace = true }
tokio = { workspace = true }
